# Generated by Django 5.1 on 2024-08-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('auteur', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('Livre', 'Livre'), ('CD', 'CD'), ('DVD', 'DVD'), ('Jeu de plateau', 'Jeu de plateau')], max_length=50)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
