# Generated by Django 5.1 on 2024-08-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaires', '0002_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='JeuDePlateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('auteur', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('Livre', 'Livre'), ('CD', 'CD'), ('DVD', 'DVD')], max_length=50),
        ),
    ]
